### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by wherget**
These few changes make it so that all library references (in `QtNetwork`, `QtWebSockets`) use `@rpath` as their path (e7b7af8), and no `LC_RPATH` commands with the build environment's libobs location remain in `obs-websocket.so` (0f78034).
Most problems probably arise for users that build `obs-websocket.so` themselves, since the remaining references could lead to dyld trying to load two versions of Qt: the one shipped with OBS in `@rpath` and any other version on the system (e.g. the one used to build the obs-studio inside the obs-websocket build). Nevertheless I figured it would be good practice to have all paths sane even in the shipped version.

There's also a minor convenience for self-builders in that the `package-macos.sh` script doesn't error out when the `Qt*` libraries are already in the build directory. Running `install_name_tool` multiple times on the Qt libs is a no-op, since all the changes will have been applied already.

### CODE REVIEW

**Comment by RytoEX** [comment]
Regarding the failure that you noted [here](https://github.com/Palakis/obs-websocket/pull/207#issuecomment-384585075), at which point in your three commits here is that issue fixed?  It seems like the first two are needed together to solve the issue, and that third commit is a separate addition?

**Comment by wherget** [comment]
That would be correct. Would you like me to leave the addition separate?

**Comment by RytoEX** [comment]
The last commit doesn't really need to be in a separate PR, since mine is generically "macOS CI updates".  I just wanted to ascertain the purpose of each.

**Comment by RytoEX** [comment]
I later edited my comment above, but realized that it probably sent an email notification that you may have read (correctly) as having no questions needing answered.  I've removed the inserted questions and placed them in a new comment here so that a new email notification is sent.

Is the issue fixed by the first two commits only present for users who build with the CI scripts locally? Did that issue affect releases produced by the CI services? I'm just trying to fully understand the scope of the issue, whether it was introduced by my PR or if it existed before, and the other details.

**Comment by wherget** [comment]
Sorry for the delay, I got caught up in activities yesterday, and indeed I did not see your edit. I'll try to answer as best I can, however there's a mild amount of speculation involved since I had not recorded every state along the way.

My understanding is that the issue I'm fixing may arise for mac users which have a Qt installed via homebrew, irrespective of whether – but especially if – they're compiling obs-websocket themselves.

As you can see from the [CI build of your original PR](https://travis-ci.org/Palakis/obs-websocket/jobs/366717632) in the packaging step, the id (first entry) of the linked Qt libraries is still `/usr/local/opt/qt/lib/QtWebSockets.framework/Versions/5/QtWebSockets`. This may lead to `dyld` instead loding the library from that location, which will clash with the Qt shipped with OBS. This is fixed by setting the id to `@rpath/QtWebSockets` in e7b7af8 and brings the ids in line with the Qt libs shipped inside OBS, as  you can see from the [latest CI build](https://travis-ci.org/RytoEX/obs-websocket/jobs/371562294):
```
$ otool -L /Applications/OBS.app/Contents/Resources/bin/QtCore
/Applications/OBS.app/Contents/Resources/bin/QtCore:
	@rpath/QtCore (compatibility version 5.10.0, current version 5.10.1)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
[...]
```

The issue is further conflated by something which you unfortunately don't see in the CI build:
```
$ git log --oneline -n 1
b970691 (HEAD, origin/ci-macos-updates) CI(macOS): Split off obs-studio build task
$ otool -l obs-websocket.so
obs-websocket.so:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           8    22       2576 0x00018085
[...]
Load command 18
          cmd LC_RPATH
      cmdsize 72
         path /Users/<redacted>/obs-studio/build/libobs (offset 12)
Load command 19
          cmd LC_RPATH
      cmdsize 112
         path /Users/<redacted>/obs-websocket/build/../../obs-studio/build/UI/obs-frontend-api (offset 12)
```
The path to the intermediate-build obs is baked into the RPATH of `obs-websocket`, which in turn may lead to dyld loading `libobs` from there, which in turn may again lead to loading Qt from `/usr/local/opt` (since it is still baked into `libobs` there). But that should only make a difference if you leave the intermediate build hang around. At any rate, it seemed bad practive to me to leave these artifacts from the build process in the binary, so 0f78034 makes it such that the LC_RPATH commands are not generated at all.

In summary:
- No, the issue is also present for __some__ users which don't build their own version.
- Yes, it affects CI artifacts.
- No, it was not introduced by your PR.

I just managed to reproduce the error output on the current state of your PR (note the `Which one is undefined.`, so there is an element of chance in encountering bugs caused by this state):
```
$ /Applications/OBS.app/Contents/Resources/bin/obs
objc[69557]: Class QMacAutoReleasePoolTracker is implemented in both /Applications/OBS.app/Contents/Resources/bin/QtCore (0x5f262c8) and /usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Versions/5/QtCore (0xa66b2c8). One of the two will be used. Which one is undefined.
objc[69557]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Applications/OBS.app/Contents/Resources/bin/QtCore (0x5f26340) and /usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Versions/5/QtCore (0xa66b340). One of the two will be used. Which one is undefined.
objc[69557]: Class RunLoopModeTracker is implemented in both /Applications/OBS.app/Contents/Resources/bin/QtCore (0x5f26368) and /usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Versions/5/QtCore (0xa66b368). One of the two will be used. Which one is undefined.
QObject::moveToThread: Current thread (0x7fdd15201fd0) is not the object's thread (0x7fdd153014c0).
Cannot move to target thread (0x7fdd15201fd0)

You might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Available platform plugins are: cocoa, minimal, offscreen, webgl.

Reinstalling the application may fix this problem.
Abort trap: 6
```

I also had some other weirdness along the way: `install_name_tool` didn't change the Qt path because I had an old Qt hanging around and needed to `brew cleanup` (this may warrant another change for self-builders, but is irrelevant for CI) ; obs-websocket did load but didn't accept any connections (which I couldn't debug but am inclined to attribute to dyld rolling the player-killing dice).

I hope that clears up some points for you. If you have further questions let me know.

**Comment by RytoEX** [comment]
> No, it was not introduced by your PR.

This was really the main part I wanted to discuss.  If it's not introduced by this PR, then I think you should make it a separate PR as it's independent and solves a specific and different problem.  Also, if I merge your changes into my PR branch (possibly with changes), and then @Palakis merges those into obs-websocket/master, it will probably show Palakis as the committer, but who would it credit as the author?  From some light reading, Git and GitHub currently don't fully agree on how to credit multiple authors for a single commit (GitHub does provide a "Co-authored-by" mechanism, but git itself does not).  That being the current state of affairs, I'm not sure how (or if) you would be credited for your work.  It bothers me to think that git/GitHub might not properly credit you for contribution, and that's mostly what's been on my mind since this came up.


> this may warrant another change for self-builders, but is irrelevant for CI

Since Palakis recommends that self-builders use the CI scripts, that probably needs to be fixed too.


Honestly, these seem like great fixes to me.  While it putting them into my PR might help consolidate all the changes into one PR, I am worried about getting you full credit on them, so it might be best to file them as a separate PR directly against obs-websocket.  What do you think?

**Comment by wherget** [comment]
I'd be perfectly fine with PR-ing against obs-websocket myself. Seeing as meanwhile your changes have been approved there, I don't see a reason not to go ahead with this plan.

Concerning your worries about attribution, fret not, my commits as they are won't be touched by the merges and will still retain me as Author as well as Committer. That's attribution enough for me. The merge commits however would have you (for this PR) or Palakis (for Palakis/obs-websocket#207) as Author/Committer respectively, and I think that's fine.

Feel free to close and not merge this PR as you see fit, I'll then open a new one as soon as Palakis/obs-websocket#207 lands.

**Comment by RytoEX** [comment]
@wherget https://github.com/Palakis/obs-websocket/pull/207 has been merged.

**Pull request closed without merging**
